USE store;


DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS credit_card;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS user;


DROP DATABASE store;